# python -m train --config-name=336m100 +paths.model_name=336m100
defaults:
- base
- _self_

training:
  warmup_steps: 10000
  steps:        100000
  steps_for_lr: 100000
  learning_rate: 3.0e-4

model:
  d_model: 1024
  n_q: 16
  n_k: 16
  n_v: 16
  d_head: 128
  layers: 8
  d_ff: 8192
  vocab: 32768
  rope_max_timescale: 10000
  p_threshold: 0.0
  p_threshold_steps_fraction: 0.0

checkpoint_interval: 9200
