# python -m train --config-name=c4_a100x8x4_1b +paths.model_name=1b
defaults:
- c4_a100x8_base
- _self_

num_hosts: 4

mesh:
  d: 32
  t: 1

training:
  warmup_steps: 9250
  steps:        92500
  steps_for_lr: 92500
  learning_rate: 1.0e-5
  tokens:
    batch: 256

training_data:
  streams: 4

model:
  d_model: 2048
  n_q_per_kv: 1
  n_kv: 16
  d_head: 128
  layers: 8
  d_ff: 16384
  vocab: 32768
  rope_max_timescale: 10000

checkpoint_interval: 2500