# python -m train --config-name=c4_a100x8_1b +paths.model_name=1b
defaults:
- c4_a100x8_base
- _self_

training:
  warmup_steps: 37000
  steps:        370000
  steps_for_lr: 370000
  learning_rate: 1.0e-5
  tokens:
    batch: 64

training_data:
  streams: 1

model:
  d_model: 2048
  n_q_per_kv: 1
  n_kv: 16
  d_head: 128
  layers: 8
  d_ff: 16384
  vocab: 32768
  rope_max_timescale: 10000

checkpoint_interval: 10000