training:
  seed: 0
  tokens:
    batch: 64
    len: 1024

  # AdamW optimizer parameters
  # We use AdamW following Llama2's training details, see https://arxiv.org/pdf/2307.09288.pdf section 2.2
  adam_b1: 0.9 # Exponential decay rate to track the first moment of past gradients.
  adam_b2: 0.95 # Exponential decay rate to track the second moment of past gradients.
  adam_eps: 1.e-8 # A small constant applied to denominator outside of the square root.
  adam_eps_root: 0. # A small constant applied to denominator inside the square root.
  weight_decay: 0.1 # AdamW Weight decay
  # We take inspiration from Llama2's learning rate (LR) schedule, see https://arxiv.org/pdf/2307.09288.pdf section 2.2
  # Learning rate schedule has two parts:
  # 1) Linear warmup from 0 to [learning_rate] over steps 0 to [learning_rate_schedule_steps * warmup_steps_fraction]
  # 2) Cosine decay from [learning_rate] to [learning_rate * cosine_learning_rate_final_fraction] from warmup to learning_rate_schedule_steps

  # Learning rate is not yet tuned.
  learning_rate: 3.e-4
  cosine_learning_rate_final_fraction: 0.1 

flat_tokens:
  # filespec can also be a path on a local filesystem
  filespec: 'gcs://path/to/your/dataset'   # Fill in
  streams: 1
  read_blocks_per_shuffle_buffer: 128
  sequences_per_read_block: 1024
  seed: 0
  sequence_packing: true

paths:
  # root_working_dir can also be a path on a local filesystem
  root_working_dir: 'gcs://path/to/your/outputs'

num_hosts: 1

mesh:
  d: 8
  t: 1

io:
  max_io_threads: 1024