# python -m train --config-name=c4_a100x8_270m +paths.model_name=270m
defaults:
- c4_a100x8_base
- _self_

training:
  warmup_steps: 9200
  steps:        92000
  steps_for_lr: 92000
  learning_rate: 3.0e-4

model:
  d_model: 1024
  n_q_per_kv: 1
  n_kv: 16
  d_head: 128
  layers: 8
  d_ff: 8192
  vocab: 32768
  rope_max_timescale: 10000

checkpoint_interval: 9200
