# Command to run on your CPU:
#   XLA_FLAGS=--xla_force_host_platform_device_count=8 python -m train --config-name=local_test_synthetic +paths.model_name=synthetic_000

defaults:
- base
- _self_

training:
  warmup_steps: 2
  steps:        5
  steps_for_lr: 100
  tokens:
    batch: 32
    len: 128

model:
  d_model: 256
  n_q: 4
  n_k: 2
  n_v: 2
  d_head: 32
  layers: 2
  vocab: 1280
  d_ff: 1024
  rope_max_timescale: 256
  p_threshold: 0.0
  p_threshold_steps_fraction: 0.0

paths:
  root_working_dir: '/tmp'

checkpoint_interval: 10
num_hosts: 1

mesh:
  d: 4
  t: 2

flat_tokens:
  filespec: 'synthetic_dataset.zarr'
  streams: 2
  read_blocks_per_shuffle_buffer: 8
  sequences_per_read_block: 16
  seed: 0
  sequence_packing: true